import csv
import matplotlib.pyplot as plt

samples = []
time_data = []
freq_data = []

# 1. Read the CSV file generated by the C++ engine
try:
    with open('fft_results.csv', 'r') as file:
        reader = csv.reader(file)
        next(reader)  # Skip headers
        
        for row in reader:
            samples.append(int(row[0]))
            time_data.append(float(row[1]))
            freq_data.append(float(row[2]))
except FileNotFoundError:
    print("Error: 'fft_results.csv' not found. Please run the C++ engine first.")
    exit()

# 2. Plotting the data
plt.figure(figsize=(12, 5))

# Left Subplot: Time Domain
plt.subplot(1, 2, 1)
plt.plot(samples, time_data, marker='o', color='b', linestyle='-')
plt.title("Time Domain (Input Signal)")
plt.xlabel("Sample Index")
plt.ylabel("Amplitude")
plt.grid(True)

# Right Subplot: Frequency Domain (FFT Magnitude)
plt.subplot(1, 2, 2)
plt.bar(samples, freq_data, color='orange')
plt.title("Frequency Spectrum (FFT)")
plt.xlabel("Frequency Bin (Hz)")
plt.ylabel("Magnitude")
plt.grid(True, axis='y')

plt.tight_layout()
plt.show()